### ISSUE TITLE
IRCConnector Lego should accept IRC server username and password as params

### ISSUE THREAD

**Issue by bbriggs** [bbriggs/Legobot#54]

**Comment by Mikepicker** [comment]
Hi, I've just checked the code out and I noticed that the Legobot constructor needs a "nickpass" parameter, which is sent as "PRIVMSG NickServ :IDENTIFY <nickpass>" to the irc server (by the way, I've also noticed it has no default value, so the tutorial on the readme fails since it expect you to provide a value to nickpass). Can we close this issue or you meant a different thing?

**Comment by Mikepicker** [comment]
Just proposed a fix [here](https://github.com/bbriggs/Legobot/pull/61)

**Comment by bbriggs** [comment]
I did fix that one already in develop but forgot to close the issue, you're right. My apologies!

Thank you for your PRs, I will be looking at the others shortly.

-- Briggs

**Comment by bbriggs** [comment]
Yeah, this is working on both dev and master now. Thanks for the catch.
